// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUK2UbkFlzldv5ABmcNn18YBKYDpkDXNs',
    appId: '1:93803328175:web:634088761cd7063babda5a',
    messagingSenderId: '93803328175',
    projectId: 'odolog-v1',
    authDomain: 'odolog-v1.firebaseapp.com',
    storageBucket: 'odolog-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZx9TMkgZfXThwD-n-PVUT0VqP5XolQI',
    appId: '1:93803328175:android:20b1453752b239a1abda5a',
    messagingSenderId: '93803328175',
    projectId: 'odolog-v1',
    storageBucket: 'odolog-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL87IX7nh-70lIxPveBuwrAqi5mRqbeqY',
    appId: '1:93803328175:ios:ff5d8cf6f39da1f6abda5a',
    messagingSenderId: '93803328175',
    projectId: 'odolog-v1',
    storageBucket: 'odolog-v1.firebasestorage.app',
    iosBundleId: 'com.example.odolog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL87IX7nh-70lIxPveBuwrAqi5mRqbeqY',
    appId: '1:93803328175:ios:ff5d8cf6f39da1f6abda5a',
    messagingSenderId: '93803328175',
    projectId: 'odolog-v1',
    storageBucket: 'odolog-v1.firebasestorage.app',
    iosBundleId: 'com.example.odolog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUK2UbkFlzldv5ABmcNn18YBKYDpkDXNs',
    appId: '1:93803328175:web:4d33f92d2b555989abda5a',
    messagingSenderId: '93803328175',
    projectId: 'odolog-v1',
    authDomain: 'odolog-v1.firebaseapp.com',
    storageBucket: 'odolog-v1.firebasestorage.app',
  );
}
